# Generated by Django 4.1.7 on 2023-02-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=64)),
                ("file", models.FileField(upload_to="")),
                ("fraction", models.IntegerField()),
                ("people_name", models.CharField(max_length=32)),
            ],
        ),
    ]
